language: bash
branches:
    only:
        - gh-pages
install:
    - sudo apt-get install software-properties-common python-software-properties ed
    - sudo add-apt-repository -y ppa:marutter/rrutter
    - sudo apt-get update
    - sudo apt-get install r-cran-rjava python-pip
    - sudo R CMD javareconf
    - sudo R --no-save <<< 'install.packages("devtools", repos="http://cran.rstudio.com/")'
    - sudo R --no-save <<< 'install.packages("pander", repos="http://cran.rstudio.com/")'
    - sudo R --no-save <<< 'install.packages("knitr", repos="http://cran.rstudio.com/")'
    - sudo R --no-save <<< 'install.packages("mlr", repos="http://cran.rstudio.com/", dependencies = TRUE)'
    - sudo R --no-save <<< 'library("devtools"); install_github("berndbischl/mlr")'
    - sudo R --no-save <<< 'library("devtools"); install_github("berndbischl/ParamHelpers")'
    - sudo pip install mkdocs
script:
    - cd tutorial
    - ./build || ./build || ./build
notifications:
  email:
    recipients:
        - larsko@cs.ubc.ca
    on_success: change
    on_failure: always
