language: bash
branches:
    only:
        - gh-pages
install:
    - sudo apt-get install r-cran-rjava python-pip
    - sudo R CMD javareconf
    - R --no-save <<< 'install.packages("devtools", repos="http://cran.rstudio.com/")'
    - R --no-save <<< 'install.packages("mlr", repos="http://cran.rstudio.com/", dependencies = TRUE)'
    - R --no-save <<< 'library("devtools"); install_github("berndbischl/mlr")'
    - sudo pip install mkdocs
script:
    - cd tutorial
    - ./build
notifications:
  email:
    recipients:
        - larsko@cs.ubc.ca
    on_success: change
    on_failure: always
