language: bash
branches:
    only:
        - gh-pages
install:
    - sudo apt-get update
    - sudo apt-get install software-properties-common python-software-properties ed wget unzip
    - sudo add-apt-repository -y ppa:marutter/rrutter
    - sudo apt-get update
    - sudo apt-get install r-cran-rjava python-pip
    - sudo R CMD javareconf
    - sudo apt-get build-dep r-cran-rgl 
    - sudo R --no-save <<< 'install.packages("devtools", repos="http://cran.rstudio.com/")'
    - sudo R --no-save <<< 'install.packages("pander", repos="http://cran.rstudio.com/")'
    - sudo R --no-save <<< 'install.packages("knitr", repos="http://cran.rstudio.com/")'
    - sudo R --no-save <<< 'install.packages("mlr", repos="http://cran.rstudio.com/", dependencies = TRUE)'
    - sudo R --no-save <<< 'library("devtools"); install_github("berndbischl/mlr")'
    - sudo R --no-save <<< 'library("devtools"); install_github("berndbischl/ParamHelpers")'
    - sudo pip install mkdocs
    - wget https://github.com/mitya57/python-markdown-math/archive/master.zip
    - unzip master.zip
    - cd python-markdown-math-master && sudo python setup.py install && cd ..
script:
    - cd tutorial
    - ./build || ./build || ./build
notifications:
  email:
    recipients:
        - larsko@cs.ubc.ca
        - schiffner@math.uni-duesseldorf.de
    on_success: change
    on_failure: always
