env:
  global:
  - secure: "oZCCuJbRCV3GyGxDxAflWUKohCgNv9TtGLgdXWV4YVjIYqqSCBl0sSwv+eCE6zVDji6bTM20NK6v5l0DbpM+TCk5vQFL8cP/LKgdFMqJm88/fCMqIX5QPk0uafd0Twpni6Rm+iUECxZJS63HL7vppz2WKnnjb2ZV6avPold+E1Pn1xboAjrQ0B4yMGKpy2KjzFbfEDMfVITO6SSNc9z7Jdii9Kf17NkY8MBPUJ8CkQQcN3UfBKRx6O0P8FnA9gj3nc1Sf9EacRtovhLBQuOVGD/uTbchV2UBMdBnhVk+39qEEsBB4SPyaI4FT9t6jJoqBYpvpQU0xhJXGcERppmMsNGe8nTniAfPQsT8vQs1pyYbnahkM3AUj7/lbOjVfzE1IJ7ExxkfGVeEUQr5XA3RlD3qJgt6hU4GT04vF4zN3IHPGlc8jjv96tX7C/f6axxLuM+20aRzwc5kM2+qlWwdWDj9r0Ir9ieA4t71zbgrAPrcw+Mt8S9p3DeXgj1R6MouT/1uqSdrKTnIVQS906acb0mPh9Tpb0WX7zAWr1WScJXVpvVyiOwWyR/MpMjkLFiRS9GcdiygudFdBS3qkHkgPuhV4pzu/r03e5rbwF/FC7CiCcIYTU7VjE4/NHE+awnXU51pfbjWSBqWuDg7ClXwfxwFWvwxZDPfCt3i+rW5sqs="

language: bash
branches:
    only:
        - gh-pages
install:
    - sudo apt-get update
    - sudo apt-get install software-properties-common python-software-properties ed wget unzip
    - sudo add-apt-repository -y ppa:marutter/rrutter
    - sudo add-apt-repository -y ppa:marutter/c2d4u
    - sudo apt-get install -y libgmp-dev
    - sudo apt-get update
    - sudo apt-get install r-cran-rjava python-pip
    - sudo R CMD javareconf
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install gcc-4.8
    - sudo apt-get -qq install g++-4.8
    - sudo apt-get install -qq gfortran-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-4.8 90
    - sudo apt-get build-dep r-cran-rgl
    #- sudo R --no-save <<< 'install.packages(c("devtools", "pander", "knitr", "mlr", "kknn", "mRMRe", "Hmisc"), dependencies = TRUE, Ncpus = 2, repos="http://cran.rstudio.com/")'
    - sudo apt-get install ada adabag brnn bst care caret checkmate class clue cluster clusterSim clValid cmaes CoxBoost crs Cubist DiceKriging DiceOptim DiscriMiner deepnet e1071 earth elasticnet elmNN emoa fields flare FNN frbs FSelector gbm GenSA ggplot2 ggvis glmnet Hmisc irace kernlab kknn klaR knitr kohonen laGP LiblineaR lqa MASS mboost mco mda mlbench modeltools mRMRe neuralnet nnet nodeHarvest pamr party penalized pls plyr pROC randomForest randomForestSRC reshape2 RCurl RSNNS rFerns rjson rmarkdown robustbase ROCR rpart rrlda rsm RWeka sda shiny sparsediscrim sparseLDA stepPlr stringi SwarmSVM testthat tgp TH.data XML
    - sudo R --no-save <<< 'library("devtools"); install_github("berndbischl/ParamHelpers")'
    - sudo R --no-save <<< 'library("devtools"); install_github("mlr-org/mlr", dependencies = TRUE)'
    - curl -L https://raw.githubusercontent.com/mllg/travis-r-tools/master/update-packages.r -o /tmp/update-packages.r
    - Rscript /tmp/update-packages.r
    - sudo pip install mkdocs
    - wget https://github.com/mitya57/python-markdown-math/archive/master.zip
    - unzip master.zip
    - cd python-markdown-math-master && sudo python setup.py install && cd ..
script:
    - ./build || ./build || ./build || ./build

after_success:
    - git checkout gh-pages
    - git config user.name $GIT_NAME
    - git config user.email $GIT_EMAIL
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://$GH_TOKEN:@github.com" >> .git/credentials
    - git config push.default matching
    - git add devel
    - git commit -a -m "update auto-generated tutorial pages [ci skip]"
    - git push

notifications:
  email:
    recipients:
        - bernd_bischl@gmx.net
        - larsko@cs.ubc.ca
        - schiffner@math.uni-duesseldorf.de
        - travis.mlr@jakob-r.de
    on_success: change
    on_failure: always
