env:
  global:
  - secure: "oZCCuJbRCV3GyGxDxAflWUKohCgNv9TtGLgdXWV4YVjIYqqSCBl0sSwv+eCE6zVDji6bTM20NK6v5l0DbpM+TCk5vQFL8cP/LKgdFMqJm88/fCMqIX5QPk0uafd0Twpni6Rm+iUECxZJS63HL7vppz2WKnnjb2ZV6avPold+E1Pn1xboAjrQ0B4yMGKpy2KjzFbfEDMfVITO6SSNc9z7Jdii9Kf17NkY8MBPUJ8CkQQcN3UfBKRx6O0P8FnA9gj3nc1Sf9EacRtovhLBQuOVGD/uTbchV2UBMdBnhVk+39qEEsBB4SPyaI4FT9t6jJoqBYpvpQU0xhJXGcERppmMsNGe8nTniAfPQsT8vQs1pyYbnahkM3AUj7/lbOjVfzE1IJ7ExxkfGVeEUQr5XA3RlD3qJgt6hU4GT04vF4zN3IHPGlc8jjv96tX7C/f6axxLuM+20aRzwc5kM2+qlWwdWDj9r0Ir9ieA4t71zbgrAPrcw+Mt8S9p3DeXgj1R6MouT/1uqSdrKTnIVQS906acb0mPh9Tpb0WX7zAWr1WScJXVpvVyiOwWyR/MpMjkLFiRS9GcdiygudFdBS3qkHkgPuhV4pzu/r03e5rbwF/FC7CiCcIYTU7VjE4/NHE+awnXU51pfbjWSBqWuDg7ClXwfxwFWvwxZDPfCt3i+rW5sqs="

language: bash
branches:
    only:
        - gh-pages
install:
    - sudo apt-get update
    - sudo apt-get install software-properties-common python-software-properties ed wget unzip
    - sudo add-apt-repository -y ppa:marutter/rrutter
    - sudo apt-get update
    - sudo apt-get install r-cran-rjava python-pip
    - sudo R CMD javareconf
    - sudo apt-get build-dep r-cran-rgl 
    - sudo R --no-save <<< 'install.packages("devtools", repos="http://cran.rstudio.com/")'
    - sudo R --no-save <<< 'install.packages("pander", repos="http://cran.rstudio.com/")'
    - sudo R --no-save <<< 'install.packages("knitr", repos="http://cran.rstudio.com/")'
    - sudo R --no-save <<< 'install.packages("mlr", repos="http://cran.rstudio.com/", dependencies = TRUE)'
    - sudo R --no-save <<< 'library("devtools"); install_github("berndbischl/mlr")'
    - sudo R --no-save <<< 'library("devtools"); install_github("berndbischl/ParamHelpers")'
    - sudo pip install mkdocs
    - wget https://github.com/mitya57/python-markdown-math/archive/master.zip
    - unzip master.zip
    - cd python-markdown-math-master && sudo python setup.py install && cd ..
script:
    - cd tutorial
    - ./build || ./build || ./build

after_success:
    - git config user.name $GIT_NAME
    - git config user.email $GIT_EMAIL
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://$GH_TOKEN:@github.com" >> .git/credentials
    - git commit -a -m "update auto-generated tutorial pages"
    - git push

notifications:
  email:
    recipients:
        - larsko@cs.ubc.ca
        - schiffner@math.uni-duesseldorf.de
    on_success: change
    on_failure: always
