language: bash
branches:
    only:
        - gh-pages
r_github_packages:
    - berndbischl/BBmisc
    - berndbischl/mlr
    - berndbischl/parallelMap
    - berndbischl/ParamHelpers
    - mllg/checkmate
apt_packages:
    - r-cran-rjava
    - python-pip
before_script:
    - sudo R CMD javareconf
    - R <<< 'install.packages("devtools", repos="http://cran.rstudio.com/")'
    - R <<< 'install.packages("mlr", repos="http://cran.rstudio.com/", dependencies = TRUE)'
    - R <<< 'library("devtools"); install_github("berndbischl/mlr")'
    - sudo pip install mkdocs
script:
    - cd tutorial
    - ./build
notifications:
  email:
    recipients:
        - larsko@cs.ubc.ca
    on_success: change
    on_failure: always
